// <auto-generated />
using System;
using Acts.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acts.Api.Migrations
{
    [DbContext(typeof(ActsDbContext))]
    [Migration("20260222222049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Acts.Api.Models.AstronautDetail", b =>
                {
                    b.Property<int>("DutyId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DutyId");

                    b.ToTable("AstronautDetail");
                });

            modelBuilder.Entity("Acts.Api.Models.AstronautDuty", b =>
                {
                    b.Property<int>("DutyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DutyId");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("EndDate IS NULL");

                    b.ToTable("AstronautDuty");
                });

            modelBuilder.Entity("Acts.Api.Models.ExternalDuty", b =>
                {
                    b.Property<int>("DutyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DutyId");

                    b.HasIndex("PersonId");

                    b.ToTable("ExternalDuty");
                });

            modelBuilder.Entity("Acts.Api.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Acts.Api.Models.AstronautDetail", b =>
                {
                    b.HasOne("Acts.Api.Models.AstronautDuty", "AstronautDuty")
                        .WithOne("AstronautDetail")
                        .HasForeignKey("Acts.Api.Models.AstronautDetail", "DutyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AstronautDuty");
                });

            modelBuilder.Entity("Acts.Api.Models.AstronautDuty", b =>
                {
                    b.HasOne("Acts.Api.Models.Person", "Person")
                        .WithMany("AstronautDuties")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Acts.Api.Models.ExternalDuty", b =>
                {
                    b.HasOne("Acts.Api.Models.Person", "Person")
                        .WithMany("ExternalDuties")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Acts.Api.Models.AstronautDuty", b =>
                {
                    b.Navigation("AstronautDetail");
                });

            modelBuilder.Entity("Acts.Api.Models.Person", b =>
                {
                    b.Navigation("AstronautDuties");

                    b.Navigation("ExternalDuties");
                });
#pragma warning restore 612, 618
        }
    }
}
